# Generated by Django 3.2.10 on 2022-01-16 16:03

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', editable=False, length=8, max_length=8, prefix='')),
                ('valid', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='core.brand')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.customer')),
                ('discount_code', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='core.discountcode')),
            ],
        ),
    ]
